apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-php-docker-helloworld
  namespace: helloworld-ns
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: example-php-docker-helloworld
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          env:
          - name: MEM_TOTAL_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory