apiVersion: v1
kind: Service
metadata:
  name: example-php-docker-helloworld
  labels:
    app: example-php-docker-helloworld
spec:
  ports:
    - port: 8080
  selector:
    app: example-php-docker-helloworld
  type: LoadBalancer