apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-php-docker-helloworld
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: example-php-docker-helloworld
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080