apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-php-docker-helloworld
  namespace: helloworld-ns  
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: example-php-docker-helloworld
          resources:
            limits:
              memory: 1250Mi
            requests:
              memory: 1250Mi
          env:
          - name: MEM_TOTAL_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory